---
  - name: Collection playbook test
    hosts: localhost
    collections:
      - my_own_collection
    vars:
      - path: "./collection_test.txt"
      - content: "Test content"
    roles:
      - single_task_role
